---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sealed-secrets
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
  values:
    fullNameOverride: sealed-secrets-controller
  install:
    createNamespace: true
  interval: 1m0s
  targetNamespace: sealed-secrets
