# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#  name: trivy-system
# ---
# apiVersion: source.toolkit.fluxcd.io/v1beta2
# kind: HelmRepository
# metadata:
#  name: trivy-operator
#  namespace: flux-system
# spec:
#  interval: 60m
#  url: https://aquasecurity.github.io/helm-charts/

# ---
# apiVersion: helm.toolkit.fluxcd.io/v2beta1
# kind: HelmRelease
# metadata:
#  name: trivy-operator
#  namespace: trivy-system
# spec:
#  chart:
#    spec:
#      chart: trivy-operator
#      sourceRef:
#        kind: HelmRepository
#        name: trivy-operator
#        namespace: flux-system
#      version: 0.15.1
#  interval: 60m
#  values:
#    trivy:
#      ignoreUnfixed: true
#  install:
#    crds: CreateReplace
#    createNamespace: true

